language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t levenglick/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true levenglick/test npm test -- --coverage

after_success:
  - docker build -t levenglick/multi-client ./client
  - docker build -t levenglick/multi-nginx ./nginx
  - docker build -t levenglick/multi-server ./server
  - docker build -t levenglick/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# 
  - docker push levenglick/multi-client
  - docker push levenglick/multi-nginx
  - docker push levenglick/multi-server
  - docker push levenglick/multi-worker